// Header-level checks that don't belong to authentication, the URL scan, or the
// body heuristics. Individually most of these are weak; the scoring model treats
// them as corroboration rather than as findings that stand on their own.

import { registrableDomain } from './domains';
import type { AuthCheckResult, HeaderAnomalyResult, ReceivedChainAnalysis, Signal } from './types';

// A real auth failure, not merely "not a perfect pass" — SPF softfail or an
// absent DMARC policy is common and mostly harmless on its own, so gating the
// thread-hijack check on those too would make it fire on a large share of
// ordinary bulk mail replies. It's reserved for the signals that mean
// something actually failed.
const HARD_AUTH_FAILURE_IDS = new Set(['dmarc_fail', 'dmarc_enforced', 'spf_fail', 'dkim_fail']);

// Mailer strings that indicate the message was generated by a script rather
// than sent from a mail client or an established sending platform. PHPMailer in
// particular is the default in a large share of off-the-shelf phishing kits.
const SCRIPT_MAILER_PATTERNS: { pattern: RegExp; name: string }[] = [
  { pattern: /phpmailer/i, name: 'PHPMailer' },
  { pattern: /\bswiftmailer\b/i, name: 'SwiftMailer' },
  { pattern: /\bphp\/\d/i, name: 'a raw PHP script' },
  { pattern: /\bpython[-\s]?(?:requests|smtplib)\b/i, name: 'a Python script' },
  { pattern: /\bperl\b/i, name: 'a Perl script' },
  { pattern: /\bsendmail\b.*\bscript\b/i, name: 'a sendmail script' },
];

function headerText(headers: Map<string, unknown>, key: string): string | null {
  const value = headers.get(key);
  if (typeof value === 'string') return value;
  if (Array.isArray(value)) {
    const first = value.find((v) => typeof v === 'string');
    return typeof first === 'string' ? first : null;
  }
  if (value && typeof value === 'object' && 'text' in value) {
    const text = (value as { text: unknown }).text;
    return typeof text === 'string' ? text : null;
  }
  return null;
}

function domainOf(address: string | null | undefined): string | null {
  if (!address) return null;
  const match = String(address).match(/@([^\s>,;]+)/);
  return match ? registrableDomain(match[1].toLowerCase().replace(/[>\s]+$/, '')) : null;
}

function parseDate(value: string | null): number | null {
  if (!value) return null;
  const parsed = new Date(value).getTime();
  return Number.isNaN(parsed) ? null : parsed;
}

function checkHeaderAnomalies(
  headers: Map<string, unknown> | null,
  headerLines: { key: string; line: string }[],
  chain: ReceivedChainAnalysis | null,
  auth: AuthCheckResult
): HeaderAnomalyResult {
  if (!headers) {
    return { signals: [], messageIdDomain: null, mailer: null };
  }

  const signals: Signal[] = [];
  const keys = new Set(headerLines.map((h) => h.key.toLowerCase()));

  const fromDomain = domainOf(headerText(headers, 'from'));
  const messageId = headerText(headers, 'message-id');
  const messageIdDomain = messageId ? domainOf(messageId.replace(/[<>]/g, '')) : null;

  // The Message-ID is stamped by whatever system generated the message, so a
  // domain that doesn't match the sender is a hint the two are different
  // parties. Kept at low severity deliberately: every ESP on earth trips this
  // legitimately, which is exactly why it shouldn't score on its own.
  if (fromDomain && messageIdDomain && fromDomain !== messageIdDomain) {
    signals.push({
      id: 'message_id_domain_mismatch',
      category: 'identity',
      severity: 'low',
      label: 'Message-ID From a Different Domain',
      detail: `The Message-ID was generated by "${messageIdDomain}" while the message claims to be from "${fromDomain}". Common and harmless for mail sent through a marketing or CRM platform, so weigh it alongside the other findings.`,
    });
  }

  if (!keys.has('message-id')) {
    signals.push({
      id: 'missing_message_id',
      category: 'identity',
      severity: 'low',
      label: 'No Message-ID Header',
      detail: 'The message carries no Message-ID. Practically all mail from real clients and platforms has one; scripted senders frequently omit it.',
    });
  }

  const mailerRaw = headerText(headers, 'x-mailer') || headerText(headers, 'user-agent');
  const scriptMailer = mailerRaw
    ? SCRIPT_MAILER_PATTERNS.find((m) => m.pattern.test(mailerRaw))
    : undefined;

  if (scriptMailer) {
    signals.push({
      id: 'script_generated_mail',
      category: 'infrastructure',
      severity: 'medium',
      label: 'Sent by a Script, Not a Mail Client',
      detail: `The X-Mailer header identifies ${scriptMailer.name} ("${mailerRaw}"). Bulk senders use platforms; this pattern is typical of a phishing kit or a compromised web host sending directly.`,
      mitre: ['T1566'],
    });
  }

  // A web host sending mail records the script that called it. Legitimate
  // transactional mail from a real platform does not carry this.
  if (keys.has('x-php-originating-script')) {
    signals.push({
      id: 'php_originating_script',
      category: 'infrastructure',
      severity: 'medium',
      label: 'Sent From a Web Script',
      detail: 'An X-PHP-Originating-Script header is present, meaning this was sent by a PHP script on a web server. On mail claiming to be from a large brand, that usually means a compromised host.',
      mitre: ['T1566'],
    });
  }

  // The Date header is author-controlled; Received timestamps are not. A large
  // gap means the message was backdated, usually so it sorts out of sight or
  // appears to predate something. Uses the most recent hop deliberately —
  // "when did this actually arrive at the point we're looking at it from",
  // which is a different question from the authserv-id check below (which
  // needs the *origin* hop instead — see its own comment).
  const dateHeader = parseDate(headerText(headers, 'date'));
  const mostRecentHop = chain && chain.hops.length > 0 ? chain.hops[chain.hops.length - 1] : null;
  const deliveredAt = mostRecentHop ? parseDate(mostRecentHop.timestamp) : null;

  if (dateHeader !== null && deliveredAt !== null) {
    const skewHours = Math.abs(deliveredAt - dateHeader) / 3_600_000;
    if (skewHours > 48) {
      signals.push({
        id: 'date_header_skew',
        category: 'infrastructure',
        severity: 'medium',
        label: 'Sending Date Does Not Match Delivery',
        detail: `The Date header is ${Math.round(skewHours)} hours away from when the mail servers actually handled the message. The Date is set by the sender and the Received timestamps are not, so a gap this large means it was backdated.`,
        mitre: ['T1656'],
      });
    }
  }

  if (!keys.has('date')) {
    signals.push({
      id: 'missing_date_header',
      category: 'identity',
      severity: 'low',
      label: 'No Date Header',
      detail: 'The message has no Date header, which is required by the mail standards and present on essentially all legitimate mail.',
    });
  }

  // The claimed authserv-id should belong to the same organization as the
  // server that actually handled the message's entry into real mail
  // infrastructure — comparing registrable domains (not exact hostnames)
  // absorbs ordinary internal routing naming differences within one
  // organization (mx.google.com vs a specific mail-sor-*.google.com relay is
  // still google.com either way). A genuine mismatch means the header claims
  // a different authenticating server than the one the delivery chain itself
  // shows, which is exactly the shape of a hand-crafted Authentication-
  // Results header inserted before the message ever reached a real mail
  // server. Kept at medium rather than high: a security gateway or filtering
  // service legitimately adds its own authserv-id distinct from the
  // underlying mail server's hostname, so this needs weighing alongside
  // other findings rather than trusted alone.
  //
  // Reads auth.selectedAuthservId — the exact same header authCheck.ts
  // selected for SPF/DKIM/DMARC pass/fail purposes — rather than
  // independently re-deriving "the first occurrence" from headerLines the
  // way this used to. That independence was itself a real gap: authCheck.ts
  // selects the *oldest* surviving header (see its own selection comment),
  // while the old extractAuthservId() here picked the *first* (newest)
  // occurrence unconditionally — two different headers for a forged-trailing-
  // header message, so this check validated the genuine header and stayed
  // silent no matter what authserv-id the forged one claimed, regardless of
  // what actually got scored. Compared against the *origin* hop
  // (chain.hops[0]) rather than the most recent one for the same reason:
  // selectedAuthservId now represents the oldest/origin hop's own claim, so
  // it needs to be checked against the origin hop it corresponds to, not the
  // most recent one date_header_skew above uses — comparing an origin-hop
  // header against the most-recent hop would misfire on every ordinary
  // multi-hop forward.
  const authservId = auth.selectedAuthservId;
  const originHop = chain && chain.hops.length > 0 ? chain.hops[0] : null;
  if (authservId && authservId.includes('.') && originHop) {
    const deliveryHost = originHop.by || originHop.reverseDns;
    if (deliveryHost && registrableDomain(authservId) !== registrableDomain(deliveryHost)) {
      signals.push({
        id: 'authserv_id_mismatch',
        category: 'authentication',
        severity: 'medium',
        label: 'Authentication-Results Claims a Different Server Than Delivered It',
        detail: `The Authentication-Results header claims to be from "${authservId}", but the message's own delivery chain shows it was actually received by "${deliveryHost}". A security gateway in the chain can legitimately explain this, but it is also the shape of an Authentication-Results header written by whoever sent the message rather than by a real mail server — this tool has no way to independently verify SPF/DKIM/DMARC itself, so a header claiming a pass from a server the delivery chain doesn't corroborate is worth extra scrutiny.`,
        mitre: ['T1656'],
      });
    }
  }

  // A message presenting as a reply or forward inside an existing thread
  // (In-Reply-To/References — technical headers a real mail client generates
  // from an actual prior message, not something a phishing kit typically
  // bothers forging) that simultaneously fails real authentication is a
  // specific, well-known pattern: either the account sending it is genuinely
  // compromised and mailing from unfamiliar infrastructure, or the thread
  // headers were copied from a real message to make an unrelated one look
  // like a continuation of it. Plain generic phishing has no reason to fake
  // thread continuity at all, which is what makes this combination distinct
  // from — and stronger than — an authentication failure on its own.
  const subject = headerText(headers, 'subject') || '';
  const looksLikeReply = /^(re|fwd?)\s*:/i.test(subject.trim());
  const hasThreadHeaders = keys.has('in-reply-to') || keys.has('references');
  const hasHardAuthFailure = auth.signals.some((s) => HARD_AUTH_FAILURE_IDS.has(s.id));

  if (looksLikeReply && hasThreadHeaders && hasHardAuthFailure) {
    signals.push({
      id: 'thread_hijack_pattern',
      category: 'identity',
      severity: 'high',
      label: 'Presents as a Thread Reply, But Fails Authentication',
      detail: 'The subject and headers present this as a reply within an existing conversation, but the message fails a real authentication check. A genuine continuation of a real thread from the real correspondent should authenticate cleanly — this combination points to a compromised account or a hijacked thread, not ordinary phishing, which has no reason to fake thread continuity at all.',
      mitre: ['T1656', 'T1534'],
    });
  }

  // Benign: the machinery of a legitimate bulk sender. Forgeable, so it only
  // nudges the score, and only when nothing serious fired (see lib/signals.ts).
  if (keys.has('list-unsubscribe') && keys.has('message-id')) {
    signals.push({
      id: 'bulk_sender_headers',
      category: 'infrastructure',
      severity: 'info',
      benign: true,
      label: 'Standard Bulk-Sender Headers Present',
      detail: 'The message carries List-Unsubscribe and a Message-ID, the headers a legitimate mailing platform adds. These can be forged, but phishing kits usually do not bother.',
    });
  }

  return { signals, messageIdDomain, mailer: mailerRaw };
}

export { checkHeaderAnomalies };
