"""Header-level checks that don't belong to authentication, the URL scan, or
the body heuristics.

Port of ``typescript/src/headerAnomalies.ts``.

Individually most of these are weak; the scoring model treats them as
corroboration rather than as findings that stand on their own.
"""

from __future__ import annotations

import re
from email.utils import parsedate_to_datetime

from .domains import registrable_domain
from .types import (
    AuthCheckResult,
    HeaderAnomalyResult,
    HeaderLine,
    ReceivedChainAnalysis,
    Signal,
)

# A real auth failure, not merely "not a perfect pass" — SPF softfail or an
# absent DMARC policy is common and mostly harmless on its own, so gating the
# thread-hijack check on those too would make it fire on a large share of
# ordinary bulk mail replies. It's reserved for the signals that mean
# something actually failed.
_HARD_AUTH_FAILURE_IDS = frozenset(
    {"dmarc_fail", "dmarc_enforced", "spf_fail", "dkim_fail"}
)

# Mailer strings that indicate the message was generated by a script rather
# than sent from a mail client or an established sending platform. PHPMailer
# in particular is the default in a large share of off-the-shelf phishing kits.
_SCRIPT_MAILER_PATTERNS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"phpmailer", re.IGNORECASE), "PHPMailer"),
    (re.compile(r"\bswiftmailer\b", re.IGNORECASE), "SwiftMailer"),
    (re.compile(r"\bphp/\d", re.IGNORECASE), "a raw PHP script"),
    (
        re.compile(r"\bpython[-\s]?(?:requests|smtplib)\b", re.IGNORECASE),
        "a Python script",
    ),
    (re.compile(r"\bperl\b", re.IGNORECASE), "a Perl script"),
    (re.compile(r"\bsendmail\b.*\bscript\b", re.IGNORECASE), "a sendmail script"),
)


def _header_text(headers: dict[str, object], key: str) -> str | None:
    value = headers.get(key)
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        first = next((v for v in value if isinstance(v, str)), None)
        return first
    if isinstance(value, dict) and isinstance(value.get("text"), object):
        text = value.get("text")
        return text if isinstance(text, str) else None
    return None


_DOMAIN_RE = re.compile(r"@([^\s>,;]+)")
_TRAILING_ANGLE_WS_RE = re.compile(r"[>\s]+$")


def _domain_of(address: str | None) -> str | None:
    if not address:
        return None
    match = _DOMAIN_RE.search(str(address))
    if not match:
        return None
    return registrable_domain(_TRAILING_ANGLE_WS_RE.sub("", match.group(1).lower()))


def _parse_date(value: str | None) -> float | None:
    if not value:
        return None
    try:
        parsed = parsedate_to_datetime(value)
    except (TypeError, ValueError):
        return None
    if parsed is None:
        return None
    return parsed.timestamp() * 1000


_REPLY_FWD_RE = re.compile(r"^(re|fwd?)\s*:", re.IGNORECASE)
_ANGLE_BRACKETS_RE = re.compile(r"[<>]")


def check_header_anomalies(
    headers: dict[str, object] | None,
    header_lines: list[HeaderLine],
    chain: ReceivedChainAnalysis | None,
    auth: AuthCheckResult,
) -> HeaderAnomalyResult:
    # `headers` is `dict | None`, not `dict | None` in the falsy-empty-dict
    # sense — an empty-but-present dict (a plain-text paste with no headers
    # at all still gets `{}` from header_parser.py) must not be treated the
    # same as "there was no header block to look at."
    if headers is None:
        return {"signals": [], "messageIdDomain": None, "mailer": None}

    signals: list[Signal] = []
    keys = {h["key"].lower() for h in header_lines}

    from_domain = _domain_of(_header_text(headers, "from"))
    message_id = _header_text(headers, "message-id")
    message_id_domain = (
        _domain_of(_ANGLE_BRACKETS_RE.sub("", message_id)) if message_id else None
    )

    # The Message-ID is stamped by whatever system generated the message, so
    # a domain that doesn't match the sender is a hint the two are different
    # parties. Kept at low severity deliberately: every ESP on earth trips
    # this legitimately, which is exactly why it shouldn't score on its own.
    if from_domain and message_id_domain and from_domain != message_id_domain:
        signals.append(
            {
                "id": "message_id_domain_mismatch",
                "category": "identity",
                "severity": "low",
                "label": "Message-ID From a Different Domain",
                "detail": (
                    f'The Message-ID was generated by "{message_id_domain}" while the '
                    f'message claims to be from "{from_domain}". Common and harmless '
                    "for mail sent through a marketing or CRM platform, so weigh it "
                    "alongside the other findings."
                ),
            }
        )

    if "message-id" not in keys:
        signals.append(
            {
                "id": "missing_message_id",
                "category": "identity",
                "severity": "low",
                "label": "No Message-ID Header",
                "detail": (
                    "The message carries no Message-ID. Practically all mail from "
                    "real clients and platforms has one; scripted senders frequently "
                    "omit it."
                ),
            }
        )

    mailer_raw = _header_text(headers, "x-mailer") or _header_text(
        headers, "user-agent"
    )
    script_mailer = None
    if mailer_raw:
        for pattern, name in _SCRIPT_MAILER_PATTERNS:
            if pattern.search(mailer_raw):
                script_mailer = name
                break

    if script_mailer:
        signals.append(
            {
                "id": "script_generated_mail",
                "category": "infrastructure",
                "severity": "medium",
                "label": "Sent by a Script, Not a Mail Client",
                "detail": (
                    f'The X-Mailer header identifies {script_mailer} ("{mailer_raw}"). '
                    "Bulk senders use platforms; this pattern is typical of a "
                    "phishing kit or a compromised web host sending directly."
                ),
                "mitre": ["T1566"],
            }
        )

    # A web host sending mail records the script that called it. Legitimate
    # transactional mail from a real platform does not carry this.
    if "x-php-originating-script" in keys:
        signals.append(
            {
                "id": "php_originating_script",
                "category": "infrastructure",
                "severity": "medium",
                "label": "Sent From a Web Script",
                "detail": (
                    "An X-PHP-Originating-Script header is present, meaning this was "
                    "sent by a PHP script on a web server. On mail claiming to be from "
                    "a large brand, that usually means a compromised host."
                ),
                "mitre": ["T1566"],
            }
        )

    # The Date header is author-controlled; Received timestamps are not. A
    # large gap means the message was backdated. Uses the most recent hop
    # deliberately — "when did this actually arrive at the point we're
    # looking at it from."
    date_header = _parse_date(_header_text(headers, "date"))
    most_recent_hop = chain["hops"][-1] if chain and chain["hops"] else None
    delivered_at = (
        _parse_date(most_recent_hop["timestamp"]) if most_recent_hop else None
    )

    if date_header is not None and delivered_at is not None:
        skew_hours = abs(delivered_at - date_header) / 3_600_000
        if skew_hours > 48:
            signals.append(
                {
                    "id": "date_header_skew",
                    "category": "infrastructure",
                    "severity": "medium",
                    "label": "Sending Date Does Not Match Delivery",
                    "detail": (
                        f"The Date header is {round(skew_hours)} hours away from when "
                        "the mail servers actually handled the message. The Date is "
                        "set by the sender and the Received timestamps are not, so a "
                        "gap this large means it was backdated."
                    ),
                    "mitre": ["T1656"],
                }
            )

    if "date" not in keys:
        signals.append(
            {
                "id": "missing_date_header",
                "category": "identity",
                "severity": "low",
                "label": "No Date Header",
                "detail": (
                    "The message has no Date header, which is required by the mail "
                    "standards and present on essentially all legitimate mail."
                ),
            }
        )

    # The claimed authserv-id should belong to the same organization as the
    # server that actually handled the message's entry into real mail
    # infrastructure. Reads auth.selectedAuthservId — the exact same header
    # auth_check.py selected for SPF/DKIM/DMARC pass/fail purposes — rather
    # than independently re-deriving "the" header. Compared against the
    # *origin* hop (chain.hops[0]) since selectedAuthservId represents the
    # oldest/origin hop's own claim.
    authserv_id = auth.get("selectedAuthservId")
    origin_hop = chain["hops"][0] if chain and chain["hops"] else None
    if authserv_id and "." in authserv_id and origin_hop:
        delivery_host = origin_hop["by"] or origin_hop["reverseDns"]
        if delivery_host and registrable_domain(authserv_id) != registrable_domain(
            delivery_host
        ):
            signals.append(
                {
                    "id": "authserv_id_mismatch",
                    "category": "authentication",
                    "severity": "medium",
                    "label": (
                        "Authentication-Results Claims a Different Server Than "
                        "Delivered It"
                    ),
                    "detail": (
                        "The Authentication-Results header claims to be from "
                        f'"{authserv_id}", but the message\'s own delivery chain '
                        f'shows it was actually received by "{delivery_host}". A '
                        "security gateway in the chain can legitimately explain this, "
                        "but it is also the shape of an Authentication-Results header "
                        "written by whoever sent the message rather than by a real "
                        "mail server — this tool has no way to independently verify "
                        "SPF/DKIM/DMARC itself, so a header claiming a pass from a "
                        "server the delivery chain doesn't corroborate is worth extra "
                        "scrutiny."
                    ),
                    "mitre": ["T1656"],
                }
            )

    # A message presenting as a reply or forward inside an existing thread
    # that simultaneously fails real authentication is a specific, well-known
    # pattern: either the account sending it is genuinely compromised, or the
    # thread headers were copied from a real message to make an unrelated
    # one look like a continuation of it.
    subject = _header_text(headers, "subject") or ""
    looks_like_reply = bool(_REPLY_FWD_RE.match(subject.strip()))
    has_thread_headers = "in-reply-to" in keys or "references" in keys
    has_hard_auth_failure = any(
        s["id"] in _HARD_AUTH_FAILURE_IDS for s in auth["signals"]
    )

    if looks_like_reply and has_thread_headers and has_hard_auth_failure:
        signals.append(
            {
                "id": "thread_hijack_pattern",
                "category": "identity",
                "severity": "high",
                "label": "Presents as a Thread Reply, But Fails Authentication",
                "detail": (
                    "The subject and headers present this as a reply within an "
                    "existing conversation, but the message fails a real "
                    "authentication check. A genuine continuation of a real thread "
                    "from the real correspondent should authenticate cleanly — this "
                    "combination points to a compromised account or a hijacked thread, "
                    "not ordinary phishing, which has no reason to fake thread "
                    "continuity at all."
                ),
                "mitre": ["T1656", "T1534"],
            }
        )

    # Benign: the machinery of a legitimate bulk sender. Forgeable, so it
    # only nudges the score, and only when nothing serious fired.
    if "list-unsubscribe" in keys and "message-id" in keys:
        signals.append(
            {
                "id": "bulk_sender_headers",
                "category": "infrastructure",
                "severity": "info",
                "benign": True,
                "label": "Standard Bulk-Sender Headers Present",
                "detail": (
                    "The message carries List-Unsubscribe and a Message-ID, the "
                    "headers a legitimate mailing platform adds. These can be forged, "
                    "but phishing kits usually do not bother."
                ),
            }
        )

    return {
        "signals": signals,
        "messageIdDomain": message_id_domain,
        "mailer": mailer_raw,
    }


__all__ = ["check_header_anomalies"]
